server:
  port: 1000
spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://0.0.0.134:3306/dev
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://203.195.224.113:3306/dev
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lovingliu.example.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
